# Generated by Django 6.0.8 on 2026-09-30 12:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('trackers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricealert',
            name='triggered_at',
        ),
        migrations.AddField(
            model_name='pricealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricealert',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for notifications', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='condition',
            field=models.CharField(choices=[('ABOVE', 'Price is Above'), ('BELOW', 'Price is Below')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='trackers.ticker'),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
