# Generated by Django 6.0.8 on 2026-10-01 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_remove_pricealert_triggered_at_pricealert_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='check_interval',
            field=models.CharField(choices=[('1m', '1 хвилина'), ('1h', '1 година'), ('1d', '1 день')], default='1m', max_length=5),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='condition',
            field=models.CharField(choices=[('ABOVE', 'Above'), ('BELOW', 'Below')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
